package provision

import (
	"fmt"
	"os"
	"strings"
)

// writeStartScript writes <ServerDir>/jarjar-start.sh (0755) and, for the
// forge-like loaders, a user_jvm_args.txt carrying the heap flags. It returns
// the absolute path to the start script.
func writeStartScript(o Options) (string, error) {
	path := o.serverPath(startScriptName)

	loader := strings.ToLower(o.Loader.ID)
	if loader == "neoforge" || loader == "forge" {
		// The documented, version-independent way to pass JVM args to the
		// installer-generated run.sh is user_jvm_args.txt. run.sh reads it, so
		// the start script itself carries no -Xmx/-Xms.
		if err := writeUserJVMArgs(o); err != nil {
			return "", err
		}
	}

	if err := os.WriteFile(path, []byte(startScriptContents(o)), 0o755); err != nil {
		return "", fmt.Errorf("provision: write start script: %w", err)
	}
	return path, nil
}

// writeUserJVMArgs writes user_jvm_args.txt with the heap + Aikar tuning flags.
// It overwrites any existing file so re-provisioning takes effect, but keeps the
// well-known filename the installer's run.sh already sources.
func writeUserJVMArgs(o Options) error {
	path := o.serverPath("user_jvm_args.txt")
	var b strings.Builder
	b.WriteString("# JarJar-managed JVM args (Aikar's flags) — regenerated on re-provision.\n")
	for _, f := range aikarFlags(o.MemoryMB) {
		b.WriteString(f)
		b.WriteString("\n")
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("provision: write user_jvm_args.txt: %w", err)
	}
	return nil
}

// startScriptContents builds the shell that boots the server. It cd's into
// ServerDir so relative launch paths (fabric-server-launch.jar, ./run.sh,
// @libraries/...) resolve regardless of the caller's cwd.
func startScriptContents(o Options) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by JarJar provision — do not edit; re-run provisioning instead.\n")
	b.WriteString("set -e\n")
	b.WriteString("cd " + shellQuote(o.ServerDir) + "\n")
	b.WriteString(launchLine(o) + "\n")
	return b.String()
}

// launchLine returns the exec line that starts the server for the loader, with
// Aikar's G1GC tuning flags applied for a smooth, low-pause modded server.
func launchLine(o Options) string {
	java := shellQuote(o.JavaPath)
	jvm := strings.Join(aikarFlags(o.MemoryMB), " ")

	switch strings.ToLower(o.Loader.ID) {
	case "fabric", "quilt":
		// TODO(quilt): Quilt's installer may emit quilt-server-launch.jar rather
		// than fabric-server-launch.jar; if so, adjust the jar name here after
		// confirming on-box. Fabric always produces fabric-server-launch.jar.
		return fmt.Sprintf("exec %s %s -jar fabric-server-launch.jar nogui", java, jvm)

	case "neoforge", "forge":
		// Prefer the installer-generated run.sh (it sources user_jvm_args.txt for
		// the heap + Aikar flags). Fall back to the unix_args.txt the installer
		// drops under libraries/ if run.sh is absent for some reason.
		runSh := o.serverPath("run.sh")
		if fileExists(runSh) {
			return "exec ./run.sh nogui"
		}
		argsFile := unixArgsFile(o)
		return fmt.Sprintf("exec %s %s @%s nogui", java, jvm, argsFile)

	default:
		// Should be unreachable — installLoader validates the loader id.
		return fmt.Sprintf("exec %s %s -jar server.jar nogui", java, jvm)
	}
}

// unixArgsFile returns the version-dependent @args file the forge-like installer
// generates under libraries/. Used only as a fallback when run.sh is missing.
func unixArgsFile(o Options) string {
	switch strings.ToLower(o.Loader.ID) {
	case "neoforge":
		return fmt.Sprintf("libraries/net/neoforged/neoforge/%s/unix_args.txt", o.Loader.Version)
	case "forge":
		return fmt.Sprintf("libraries/net/minecraftforge/forge/%s-%s/unix_args.txt", o.MCVersion, o.Loader.Version)
	default:
		return "libraries/unix_args.txt"
	}
}

// buildSystemdUnit returns the full systemd service file text. The User= line is
// omitted when serviceUser is empty.
func buildSystemdUnit(serverDir, startScript, serviceUser string) string {
	var b strings.Builder
	b.WriteString("[Unit]\n")
	b.WriteString("Description=Minecraft server (JarJar)\n")
	b.WriteString("After=network-online.target\n")
	b.WriteString("Wants=network-online.target\n")
	b.WriteString("\n")
	b.WriteString("[Service]\n")
	b.WriteString("Type=simple\n")
	if serviceUser != "" {
		b.WriteString("User=" + serviceUser + "\n")
	}
	b.WriteString("WorkingDirectory=" + serverDir + "\n")
	b.WriteString("ExecStart=" + startScript + "\n")
	// Always-on: bring the server back whenever it exits (crash, OOM, or a clean
	// stop that wasn't a `systemctl stop`), and keep restarting.
	b.WriteString("Restart=always\n")
	b.WriteString("RestartSec=5\n")
	// Give the world time to save on stop before SIGKILL.
	b.WriteString("TimeoutStopSec=120\n")
	b.WriteString("\n")
	b.WriteString("[Install]\n")
	b.WriteString("WantedBy=multi-user.target\n")
	return b.String()
}

// shellQuote single-quotes a value for safe use in the POSIX start script.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
